#!/usr/bin/env python3
"""
Phase 1 - vendor the site's Google Fonts as local woff2 files.

Why this exists instead of next/font:
  ~10,000 inline styles across v2-maven hardcode the literal family names
  "Lato", "Source Serif 4" and "Inter". next/font generates hashed family
  names (__Lato_a1b2c3), so every one of those declarations would silently
  fall through to a system fallback - a sitewide typography change with no
  error. Declaring @font-face under the literal names keeps every inline
  style working untouched.

Fetches the exact stylesheet v2-maven requests, downloads the woff2 files
for the chosen subsets, and emits app/fonts.css with the same
font-family / font-style / font-weight / font-display / unicode-range
values Google served, so rendering and subset behaviour are unchanged.

READ-ONLY with respect to v2-maven.
"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
MIG = os.path.dirname(HERE)
ROOT = os.path.dirname(MIG)
APP = os.path.join(ROOT, "careorbit-next")
FONT_DIR = os.path.join(APP, "public", "fonts")
CSS_OUT = os.path.join(APP, "app", "fonts.css")

# The exact href from v2-maven's shared <helmet> block (74 pages).
GF_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Lato:ital,wght@0,300;0,400;0,700;0,900"
    "&family=Source+Serif+4:ital,opsz,wght@1,8..60,500;1,8..60,600"
    "&family=Inter:wght@400;500;600"
    "&display=swap"
)

# The site's copy is English. latin covers it; latin-ext covers the curly
# punctuation and any accented names. The cyrillic / greek / vietnamese
# subsets Google also offers are not reachable by this site's content.
KEEP_SUBSETS = {"latin", "latin-ext"}

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")

SLUG = {
    "Lato": "lato",
    "Source Serif 4": "source-serif-4",
    "Inter": "inter",
}


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)

    css = fetch(GF_URL)
    blocks = re.findall(
        r"/\*\s*([a-z0-9\-\[\]]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S
    )
    if not blocks:
        sys.exit("no @font-face blocks parsed - Google Fonts response changed")

    out = [
        "/* CareOrbit self-hosted fonts - generated by "
        "migration/scripts/vendor_fonts.py. Do not edit by hand.",
        " *",
        " * Declared under the LITERAL family names Lato / Source Serif 4 / Inter",
        " * so the inline font-family declarations carried over from v2-maven keep",
        " * resolving. Values below are exactly what Google served.",
        " */",
        "",
    ]
    kept = skipped = 0
    downloaded = []

    for subset, body in blocks:
        if subset not in KEEP_SUBSETS:
            skipped += 1
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        style = re.search(r"font-style:\s*(\w+)", body).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        url = re.search(r"src:\s*url\(([^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()

        name = "%s-%s-%s-%s.woff2" % (SLUG[family], style, weight, subset)
        dest = os.path.join(FONT_DIR, name)
        if not os.path.exists(dest):
            with open(dest, "wb") as fh:
                fh.write(fetch(url, binary=True))
        downloaded.append((name, os.path.getsize(dest)))
        kept += 1

        out.append("@font-face {")
        out.append("  font-family: '%s';" % family)
        out.append("  font-style: %s;" % style)
        out.append("  font-weight: %s;" % weight)
        out.append("  font-display: swap;")
        out.append("  src: url('/fonts/%s') format('woff2');" % name)
        out.append("  unicode-range: %s;" % urange)
        out.append("}")
        out.append("")

    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    total = sum(s for _, s in downloaded)
    print("faces kept:    %d" % kept)
    print("faces skipped: %d (subsets outside %s)" % (skipped, sorted(KEEP_SUBSETS)))
    print("total woff2:   %.1f KB" % (total / 1024))
    print("css written:   %s" % os.path.relpath(CSS_OUT, ROOT))
    for n, s in sorted(downloaded):
        print("  %-42s %6.1f KB" % (n, s / 1024))


if __name__ == "__main__":
    main()
